#!/usr/bin/env ruby
# Copyright (c) 2010 Robert Riemann <saloution@googlemail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

$KCODE = 'u'
$:.unshift File.expand_path("..", __FILE__)
require 'lib/kubeplayer.rb'

start_kubeplayer if __FILE__ == $0