# This file is generated by rbkconfig_compiler from YoutubeSettings.kcfg.
# All changes you do to this file will be lost.

require 'singleton'

class YoutubeSettings < KDE::ConfigSkeleton
  include Singleton

  class EnumQuality
    R640x360 = 0
    R854x480 = 1
    R480x360 = 2
    R1280x720 = 3
    R1920x1080 = 4
    R4096x3072 = 5
    COUNT = 6
  end

  #
  # Set Maximum quality format for videos.
  #
  def setQuality(v)
    item = findItem("Quality")
    if !item.immutable?
      item.property = @quality = Qt::Variant.fromValue(v)
    end
  end

  def quality=(v)
    setQuality(v)
  end

  #
  # Get Maximum quality format for videos.
  #
  def quality
    @quality = findItem("Quality").property
    return @quality.toInt
  end

  def initialize()
    super()

    # youtube
    @quality = Qt::Variant.fromValue(0)
    setCurrentGroup("youtube")

    valuesQuality = []
    choice = ItemEnum::Choice.new
    choice.name = "R640x360"
    valuesQuality << choice
    choice = ItemEnum::Choice.new
    choice.name = "R854x480"
    valuesQuality << choice
    choice = ItemEnum::Choice.new
    choice.name = "R480x360"
    valuesQuality << choice
    choice = ItemEnum::Choice.new
    choice.name = "R1280x720"
    valuesQuality << choice
    choice = ItemEnum::Choice.new
    choice.name = "R1920x1080"
    valuesQuality << choice
    choice = ItemEnum::Choice.new
    choice.name = "R4096x3072"
    valuesQuality << choice
    itemQuality = ItemEnum.new(currentGroup(), "Quality", @quality.toInt, valuesQuality, EnumQuality::R480x360)
    itemQuality.property = @quality
    addItem(itemQuality)
    readConfig
  end

end
