# This file is generated by rbkconfig_compiler from YoutubeSettings.kcfg.
# All changes you do to this file will be lost.

require 'singleton'

class YoutubeSettings < KDE::ConfigSkeleton
  include Singleton
  #
  # Set Maximum quality format for videos.
  #
  def setQuality(v)
    item = findItem("Quality")
    if !item.immutable?
      item.property = @quality = Qt::Variant.fromValue(v)
    end
  end

  def quality=(v)
    setQuality(v)
  end

  #
  # Get Maximum quality format for videos.
  #
  def quality
    @quality = findItem("Quality").property
    return @quality.value
  end

  def initialize()
    super()

    # youtube
    @quality = Qt::Variant.fromValue(0)
    setCurrentGroup("youtube")

    itemQuality = ItemInt.new(currentGroup(), "Quality", @quality.value, 18)
    itemQuality.property = @quality
    addItem(itemQuality)
    readConfig
  end

end
